// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/tsugi_agent.proto

// Localhost control channel between Yagura (read plane, Rust/tonic client) and
// the Tsugi agent (write plane, Go/grpc-go server).

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TsugiAgent_ListReleases_FullMethodName    = "/tsugi.agent.v1.TsugiAgent/ListReleases"
	TsugiAgent_ListDeployments_FullMethodName = "/tsugi.agent.v1.TsugiAgent/ListDeployments"
	TsugiAgent_Deploy_FullMethodName          = "/tsugi.agent.v1.TsugiAgent/Deploy"
	TsugiAgent_Rollback_FullMethodName        = "/tsugi.agent.v1.TsugiAgent/Rollback"
	TsugiAgent_Promote_FullMethodName         = "/tsugi.agent.v1.TsugiAgent/Promote"
)

// TsugiAgentClient is the client API for TsugiAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Yagura observes, Tsugi acts. Reads are unary; deploy actions server-stream the
// build/deploy log so Yagura can relay it to the browser as SSE.
type TsugiAgentClient interface {
	ListReleases(ctx context.Context, in *ListReleasesReq, opts ...grpc.CallOption) (*ListReleasesResp, error)
	ListDeployments(ctx context.Context, in *ListDeploymentsReq, opts ...grpc.CallOption) (*ListDeploymentsResp, error)
	Deploy(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	Rollback(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	Promote(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
}

type tsugiAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewTsugiAgentClient(cc grpc.ClientConnInterface) TsugiAgentClient {
	return &tsugiAgentClient{cc}
}

func (c *tsugiAgentClient) ListReleases(ctx context.Context, in *ListReleasesReq, opts ...grpc.CallOption) (*ListReleasesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReleasesResp)
	err := c.cc.Invoke(ctx, TsugiAgent_ListReleases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsugiAgentClient) ListDeployments(ctx context.Context, in *ListDeploymentsReq, opts ...grpc.CallOption) (*ListDeploymentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeploymentsResp)
	err := c.cc.Invoke(ctx, TsugiAgent_ListDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsugiAgentClient) Deploy(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TsugiAgent_ServiceDesc.Streams[0], TsugiAgent_Deploy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeployReq, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TsugiAgent_DeployClient = grpc.ServerStreamingClient[LogLine]

func (c *tsugiAgentClient) Rollback(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TsugiAgent_ServiceDesc.Streams[1], TsugiAgent_Rollback_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeployReq, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TsugiAgent_RollbackClient = grpc.ServerStreamingClient[LogLine]

func (c *tsugiAgentClient) Promote(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TsugiAgent_ServiceDesc.Streams[2], TsugiAgent_Promote_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeployReq, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TsugiAgent_PromoteClient = grpc.ServerStreamingClient[LogLine]

// TsugiAgentServer is the server API for TsugiAgent service.
// All implementations must embed UnimplementedTsugiAgentServer
// for forward compatibility.
//
// Yagura observes, Tsugi acts. Reads are unary; deploy actions server-stream the
// build/deploy log so Yagura can relay it to the browser as SSE.
type TsugiAgentServer interface {
	ListReleases(context.Context, *ListReleasesReq) (*ListReleasesResp, error)
	ListDeployments(context.Context, *ListDeploymentsReq) (*ListDeploymentsResp, error)
	Deploy(*DeployReq, grpc.ServerStreamingServer[LogLine]) error
	Rollback(*DeployReq, grpc.ServerStreamingServer[LogLine]) error
	Promote(*DeployReq, grpc.ServerStreamingServer[LogLine]) error
	mustEmbedUnimplementedTsugiAgentServer()
}

// UnimplementedTsugiAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTsugiAgentServer struct{}

func (UnimplementedTsugiAgentServer) ListReleases(context.Context, *ListReleasesReq) (*ListReleasesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReleases not implemented")
}
func (UnimplementedTsugiAgentServer) ListDeployments(context.Context, *ListDeploymentsReq) (*ListDeploymentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeployments not implemented")
}
func (UnimplementedTsugiAgentServer) Deploy(*DeployReq, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedTsugiAgentServer) Rollback(*DeployReq, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedTsugiAgentServer) Promote(*DeployReq, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedTsugiAgentServer) mustEmbedUnimplementedTsugiAgentServer() {}
func (UnimplementedTsugiAgentServer) testEmbeddedByValue()                    {}

// UnsafeTsugiAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TsugiAgentServer will
// result in compilation errors.
type UnsafeTsugiAgentServer interface {
	mustEmbedUnimplementedTsugiAgentServer()
}

func RegisterTsugiAgentServer(s grpc.ServiceRegistrar, srv TsugiAgentServer) {
	// If the following call panics, it indicates UnimplementedTsugiAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TsugiAgent_ServiceDesc, srv)
}

func _TsugiAgent_ListReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReleasesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsugiAgentServer).ListReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsugiAgent_ListReleases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsugiAgentServer).ListReleases(ctx, req.(*ListReleasesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsugiAgent_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsugiAgentServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsugiAgent_ListDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsugiAgentServer).ListDeployments(ctx, req.(*ListDeploymentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsugiAgent_Deploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TsugiAgentServer).Deploy(m, &grpc.GenericServerStream[DeployReq, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TsugiAgent_DeployServer = grpc.ServerStreamingServer[LogLine]

func _TsugiAgent_Rollback_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TsugiAgentServer).Rollback(m, &grpc.GenericServerStream[DeployReq, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TsugiAgent_RollbackServer = grpc.ServerStreamingServer[LogLine]

func _TsugiAgent_Promote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TsugiAgentServer).Promote(m, &grpc.GenericServerStream[DeployReq, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TsugiAgent_PromoteServer = grpc.ServerStreamingServer[LogLine]

// TsugiAgent_ServiceDesc is the grpc.ServiceDesc for TsugiAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TsugiAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tsugi.agent.v1.TsugiAgent",
	HandlerType: (*TsugiAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListReleases",
			Handler:    _TsugiAgent_ListReleases_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _TsugiAgent_ListDeployments_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deploy",
			Handler:       _TsugiAgent_Deploy_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Rollback",
			Handler:       _TsugiAgent_Rollback_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Promote",
			Handler:       _TsugiAgent_Promote_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/tsugi_agent.proto",
}
