// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/tsugi_agent.proto

// Localhost control channel between Yagura (read plane, Rust/tonic client) and
// the Tsugi agent (write plane, Go/grpc-go server).

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A release as deployed to one environment (denormalized release ⨝ deployment).
type Release struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"` // staging | production
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Commit        string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`                                  // version tag, e.g. v1.2.3
	DeployedAt    int64                  `protobuf:"varint,5,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"` // unix seconds; 0 if never deployed
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                            // release vocab: created/staging/production/archived
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Release) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Release) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Release) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Release) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Release) GetDeployedAt() int64 {
	if x != nil {
		return x.DeployedAt
	}
	return 0
}

func (x *Release) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// One deployment-history record: a release deployed to an environment.
type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"` // staging | production
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Commit        string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                            // deployment vocab: pending/succeeded/failed
	DeployedAt    int64                  `protobuf:"varint,5,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Deployment) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Deployment) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Deployment) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deployment) GetDeployedAt() int64 {
	if x != nil {
		return x.DeployedAt
	}
	return 0
}

// Shared by Deploy/Rollback/Promote. Rollback: commit = target (unset = previous).
// Promote: env = destination environment for the given commit.
type DeployReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	Commit        *string                `protobuf:"bytes,3,opt,name=commit,proto3,oneof" json:"commit,omitempty"` // explicit presence: unset ≠ "" (F-042)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployReq) Reset() {
	*x = DeployReq{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployReq) ProtoMessage() {}

func (x *DeployReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployReq.ProtoReflect.Descriptor instead.
func (*DeployReq) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DeployReq) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DeployReq) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *DeployReq) GetCommit() string {
	if x != nil && x.Commit != nil {
		return *x.Commit
	}
	return ""
}

// One line of streamed build/deploy output.
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`        // unix millis
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"` // stdout | stderr
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{3}
}

func (x *LogLine) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListReleasesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleasesReq) Reset() {
	*x = ListReleasesReq{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleasesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleasesReq) ProtoMessage() {}

func (x *ListReleasesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleasesReq.ProtoReflect.Descriptor instead.
func (*ListReleasesReq) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{4}
}

type ListReleasesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Releases      []*Release             `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleasesResp) Reset() {
	*x = ListReleasesResp{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleasesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleasesResp) ProtoMessage() {}

func (x *ListReleasesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleasesResp.ProtoReflect.Descriptor instead.
func (*ListReleasesResp) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListReleasesResp) GetReleases() []*Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

type ListDeploymentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsReq) Reset() {
	*x = ListDeploymentsReq{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsReq) ProtoMessage() {}

func (x *ListDeploymentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsReq.ProtoReflect.Descriptor instead.
func (*ListDeploymentsReq) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{6}
}

type ListDeploymentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResp) Reset() {
	*x = ListDeploymentsResp{}
	mi := &file_proto_tsugi_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResp) ProtoMessage() {}

func (x *ListDeploymentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tsugi_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResp.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResp) Descriptor() ([]byte, []int) {
	return file_proto_tsugi_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListDeploymentsResp) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

var File_proto_tsugi_agent_proto protoreflect.FileDescriptor

const file_proto_tsugi_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/tsugi_agent.proto\x12\x0etsugi.agent.v1\"\x98\x01\n" +
	"\aRelease\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x1f\n" +
	"\vdeployed_at\x18\x05 \x01(\x03R\n" +
	"deployedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x89\x01\n" +
	"\n" +
	"Deployment\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vdeployed_at\x18\x05 \x01(\x03R\n" +
	"deployedAt\"_\n" +
	"\tDeployReq\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x1b\n" +
	"\x06commit\x18\x03 \x01(\tH\x00R\x06commit\x88\x01\x01B\t\n" +
	"\a_commit\"E\n" +
	"\aLogLine\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x11\n" +
	"\x0fListReleasesReq\"G\n" +
	"\x10ListReleasesResp\x123\n" +
	"\breleases\x18\x01 \x03(\v2\x17.tsugi.agent.v1.ReleaseR\breleases\"\x14\n" +
	"\x12ListDeploymentsReq\"S\n" +
	"\x13ListDeploymentsResp\x12<\n" +
	"\vdeployments\x18\x01 \x03(\v2\x1a.tsugi.agent.v1.DeploymentR\vdeployments2\xfe\x02\n" +
	"\n" +
	"TsugiAgent\x12Q\n" +
	"\fListReleases\x12\x1f.tsugi.agent.v1.ListReleasesReq\x1a .tsugi.agent.v1.ListReleasesResp\x12Z\n" +
	"\x0fListDeployments\x12\".tsugi.agent.v1.ListDeploymentsReq\x1a#.tsugi.agent.v1.ListDeploymentsResp\x12>\n" +
	"\x06Deploy\x12\x19.tsugi.agent.v1.DeployReq\x1a\x17.tsugi.agent.v1.LogLine0\x01\x12@\n" +
	"\bRollback\x12\x19.tsugi.agent.v1.DeployReq\x1a\x17.tsugi.agent.v1.LogLine0\x01\x12?\n" +
	"\aPromote\x12\x19.tsugi.agent.v1.DeployReq\x1a\x17.tsugi.agent.v1.LogLine0\x01B8Z6github.com/latoulicious/Tsugi/internal/agentpb;agentpbb\x06proto3"

var (
	file_proto_tsugi_agent_proto_rawDescOnce sync.Once
	file_proto_tsugi_agent_proto_rawDescData []byte
)

func file_proto_tsugi_agent_proto_rawDescGZIP() []byte {
	file_proto_tsugi_agent_proto_rawDescOnce.Do(func() {
		file_proto_tsugi_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tsugi_agent_proto_rawDesc), len(file_proto_tsugi_agent_proto_rawDesc)))
	})
	return file_proto_tsugi_agent_proto_rawDescData
}

var file_proto_tsugi_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_tsugi_agent_proto_goTypes = []any{
	(*Release)(nil),             // 0: tsugi.agent.v1.Release
	(*Deployment)(nil),          // 1: tsugi.agent.v1.Deployment
	(*DeployReq)(nil),           // 2: tsugi.agent.v1.DeployReq
	(*LogLine)(nil),             // 3: tsugi.agent.v1.LogLine
	(*ListReleasesReq)(nil),     // 4: tsugi.agent.v1.ListReleasesReq
	(*ListReleasesResp)(nil),    // 5: tsugi.agent.v1.ListReleasesResp
	(*ListDeploymentsReq)(nil),  // 6: tsugi.agent.v1.ListDeploymentsReq
	(*ListDeploymentsResp)(nil), // 7: tsugi.agent.v1.ListDeploymentsResp
}
var file_proto_tsugi_agent_proto_depIdxs = []int32{
	0, // 0: tsugi.agent.v1.ListReleasesResp.releases:type_name -> tsugi.agent.v1.Release
	1, // 1: tsugi.agent.v1.ListDeploymentsResp.deployments:type_name -> tsugi.agent.v1.Deployment
	4, // 2: tsugi.agent.v1.TsugiAgent.ListReleases:input_type -> tsugi.agent.v1.ListReleasesReq
	6, // 3: tsugi.agent.v1.TsugiAgent.ListDeployments:input_type -> tsugi.agent.v1.ListDeploymentsReq
	2, // 4: tsugi.agent.v1.TsugiAgent.Deploy:input_type -> tsugi.agent.v1.DeployReq
	2, // 5: tsugi.agent.v1.TsugiAgent.Rollback:input_type -> tsugi.agent.v1.DeployReq
	2, // 6: tsugi.agent.v1.TsugiAgent.Promote:input_type -> tsugi.agent.v1.DeployReq
	5, // 7: tsugi.agent.v1.TsugiAgent.ListReleases:output_type -> tsugi.agent.v1.ListReleasesResp
	7, // 8: tsugi.agent.v1.TsugiAgent.ListDeployments:output_type -> tsugi.agent.v1.ListDeploymentsResp
	3, // 9: tsugi.agent.v1.TsugiAgent.Deploy:output_type -> tsugi.agent.v1.LogLine
	3, // 10: tsugi.agent.v1.TsugiAgent.Rollback:output_type -> tsugi.agent.v1.LogLine
	3, // 11: tsugi.agent.v1.TsugiAgent.Promote:output_type -> tsugi.agent.v1.LogLine
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tsugi_agent_proto_init() }
func file_proto_tsugi_agent_proto_init() {
	if File_proto_tsugi_agent_proto != nil {
		return
	}
	file_proto_tsugi_agent_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tsugi_agent_proto_rawDesc), len(file_proto_tsugi_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tsugi_agent_proto_goTypes,
		DependencyIndexes: file_proto_tsugi_agent_proto_depIdxs,
		MessageInfos:      file_proto_tsugi_agent_proto_msgTypes,
	}.Build()
	File_proto_tsugi_agent_proto = out.File
	file_proto_tsugi_agent_proto_goTypes = nil
	file_proto_tsugi_agent_proto_depIdxs = nil
}
